### ISSUE TITLE
Incorrect use of time.clock() on Linux OS

### ISSUE THREAD

**Issue by stuper27** [alessandromaggio/pythonping#11]
In network.py `def receive(self, timeout=2)` the function uses `time.clock()` to initialize `start_select.` This is fine for windows though on Linux running on an ARM architecture the line:
`elapsed_in_select = time.clock() - start_select`
results in lets say 8-10ms, then the function continues through subtracting 8-10ms from `time_left` and spends several hundreds of milliseconds going through
`packet, source = self.socket.recvfrom(self.BUFFER_SIZE)`
`return packet, source, time_left`
So after well over the specified timeout, which is also seeming hard coded to 2 seconds `def receive(self, timeout=2)` the `time_left` variable is sitting around 1.9 seconds remaining. 

The solution is simply to change all `time.clock()` to `time.time()`. I am not sure how this will affect Windows users so perhaps first identify the OS and use the most effect call.

**Comment by alessandromaggio** [comment]
👍 
Thank you, this is a really good troubleshooting!
I'll try to bring back to life my Raspberry PI and verify, and hopefully fix it ASAP. If you want you can fork me and I'll check the edits to include them in the next release.

**Comment by cveilleux** [comment]
`time.clock()` is actually deprecated since python 3.3 for this exact issue. The behavior is completely different on unix and windows.

https://docs.python.org/3.7/library/time.html#time.clock

`time.perf_counter()` appears to be the best option for maximum precision.

`time.time()` also works but is dependent on the system time, so ntp can make it drift between 2 calls.

I will provide a PR shortly.

**Comment by alessandromaggio** [comment]
Thank you! I've merged your changes in the master, and published them in the release 1.0.3 which is already out. This release also ensures sockets get closed automatically once the ping finishes, avoiding annoying warning messages.
