### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by Wa2el3ali** [alessandromaggio/pythonping#16]
Hello Alessandro,
I'm asking on how to access "success" property in a ping instance or may be executor instance?
Also, i would appreciate it if you send me documentation for this project.

Thank you in advance

**Comment by alessandromaggio** [comment]
Hello Wa2el3ali,

Ping returns a `ResponseList` object, which contains one `Response` for each ICMP message you sent (this depends on the count). The `Response` object has the success property, so to access it you would need to do `rs._responses[0].success`, where rs is the object returned by `ping()`.
Doing some means you are accessing a private propriety (`_responses`), as this class was not really meant for that. Since this is a request I received from multiple people, I will consider adding a more convenient way of obtaining the boolean status of a ping in the next release.

At the moment, the only documentation I produced about this project are the docstrings you can already find in the source code in GitHub. With them (and probably some patience), you can understand how pythonping works, bit by bit. I will consider adding more documentation and maybe creating a Wiki.

**Comment by jonathanchan** [comment]
Is there a way to see the percentage pack loss of a ping command?

I guess I'm looking for something comparable to running a ping from the (mac) termimal.

Mac Terminal ping:

> 4 packets transmitted, 0 packets received, 100.0% packet loss

vs pythonping

> Round Trip Times min/avg/max is 2000/2000.0/2000 ms

**Comment by Yuanyp8** [comment]
I ‘m also looking for the packets loss 
just like:
229 packets transmitted, 229 received, 0% packet loss, time 228000ms

**Comment by alessandromaggio** [comment]
Documentation has been expanded over the course of various releases. As of now, documentation should be added and expanded with every release and does not need a separate issue to track it any longer.
