### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Asgoret** [alessandromaggio/pythonping#36]
Use privileged mode is not good practice. How I can start ping process not using root mode?

**Comment by LuciferMorningstar** [comment]
Seconded.  I can't really use this if I have to elevate my privileges just to ping a server.

**Comment by alessandromaggio** [comment]
Unfortunately, this is not possible, that's because we are using raw sockets and that requires root privilege (as you can potentially do any kind of traffic, including spoofing other applications). We have no other way to create ICMP packets than using raw sockets, so privileged mode it's a requirement. There isn't much we can do.
