### ISSUE TITLE
"Protocol not supported" issue with protocol type

### ISSUE THREAD

**Issue by deltaflyer4747** [alessandromaggio/pythonping#40]
hw: RaspberryPi
os: Raspbian 10.1
issue:
```
  File "/usr/local/lib/python3.7/dist-packages/pythonping/__init__.py", line 52, in ping
    comm = executor.Communicator(target, provider, timeout, socket_options=options, verbose=verbose, output=out)
  File "/usr/local/lib/python3.7/dist-packages/pythonping/executor.py", line 240, in __init__
    self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)
  File "/usr/local/lib/python3.7/dist-packages/pythonping/network.py", line 30, in __init__
    self.socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, self.protocol)
  File "/usr/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 93] Protocol not supported
```

Solution (tested both on raspberry and regular machine):

```
--- executor.py_orig    2020-05-18 10:14:46.091881721 +0100
+++ executor.py 2020-05-18 10:15:34.120668253 +0100
@@ -5,6 +5,7 @@
 from . import icmp
 from . import network
 import threading
+import socket

 # Python 3.5 compatibility
 if sys.version_info[1] == 5:
@@ -237,7 +238,7 @@
         :type verbose: bool
         :param output: File where to write verbose output, defaults to stdout
         :type output: file"""
-        self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)
+        self.socket = network.Socket(target, socket.IPPROTO_ICMP, source=None, options=socket_options)
         self.provider = payload_provider
         self.timeout = timeout
         self.responses = ResponseList(verbose=verbose, output=output)
```
```
--- network.py_orig     2020-05-18 09:53:37.150080492 +0100
+++ network.py  2020-05-18 10:15:44.580410280 +0100
@@ -23,7 +23,7 @@
             self.destination = socket.gethostbyname(destination)
         except socket.gaierror as e:
             raise RuntimeError('Cannot resolve address "' + destination + '", try verify your DNS or host file')
-        self.protocol = socket.getprotobyname(protocol)
+        self.protocol = protocol
         self.buffer_size = buffer_size
         if source is not None:
             raise NotImplementedError('PythonPing currently does not support specification of source IP')
```

**Comment by alessandromaggio** [comment]
What is the code you use to generate the error?

**Comment by deltaflyer4747** [comment]
a very basic one (see below). Issue is caused by using string "icmp" and then converting that to numeral, instead of using socket type IPPROTO_ICMP. It converts to "1" as string too, but seems like it needs proper value, not just integer. 
```
from pythonping import ping
ping ("8.8.8.8", verbose=False, count=1)
```

**Comment by alessandromaggio** [comment]
Alright, make a pull request so that we can better evaluate it.

**Comment by malbers15** [comment]
The original implementation in executor.py:
`self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)`
and then in network.py:
`self.protocol = socket.getprotobyname(protocol)`

looks correct according to both python 3.5 and 3.7 documentation:
https://docs.python.org/3.5/library/socket.html#socket.getprotobyname
https://docs.python.org/3.7/library/socket.html#socket.getprotobyname

I also have run this on my rasbperry pi with python 3.7 and on the same Raspbian version (output of `cat /etc/os-release`): 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


I cannot reproduce the issue:
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> from pythonping import ping
\>>> ping("8.8.8.8", verbose=False, count=1)
Reply from 8.8.8.8, 9 bytes in 4.1ms

Round Trip Times min/avg/max is 4.1/4.1/4.1 ms
\>>> ping("8.8.8.8", verbose=True, count=1)
Reply from 8.8.8.8, 9 bytes in 4.2ms
Reply from 8.8.8.8, 9 bytes in 4.2ms

Round Trip Times min/avg/max is 4.2/4.2/4.2 ms


Whatever this issue was, I do not think it is anymore and can be closed now, unless there is something I have missed.  Please comment @alessandromaggio @deltaflyer4747

**Comment by malbers15** [comment]
Hi @alessandromaggio ,

So, I believe this is actually an issue now upon encountering it.  What I can infer from previous conversations with @deltaflyer4747 is that he was attempting to use pythonping multi-threaded as he came up with the initial POC to make it thread safe:
https://github.com/alessandromaggio/pythonping/issues/39#issuecomment-661354372

I have determined this "Protocol not supported" issue can be seen, but only when using pythonping multi-threaded, and intermittently at that.  For some reason, currently unknown to me, the proper python call for
`socket.getprotobyname('icmp')`
(which is what the call trace translates to for executor.py:
`self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)`
and then in network.py:
`self.protocol = socket.getprotobyname(protocol)`
...occasionally returns a 0 instead of a 1 in a multi-threading python usage environment.

I do not know why this is but I can confirm that replacing this way of doing things:
`socket.getprotobyname('icmp')`
with the constant:
`socket.IPPROTO_ICMP`
...does fix the issue in a multi-threaded environment as @deltaflyer4747 stated.


Can you reopen this issue and then I will begin working on a formal PR?

**Comment by malbers15** [comment]
It is a bug in python that affects 3.5, 3.6, and 3.7:
https://bugs.python.org/issue30482
"socket.getservbyname(), socket.getservbyport(), socket.getprotobyname() are not threadsafe"

I will implement a workaround.

**Comment by malbers15** [comment]
Here is the PR @alessandromaggio 
https://github.com/alessandromaggio/pythonping/pull/56
