### ISSUE TITLE
Cannot import pythonping in python2

### ISSUE THREAD

**Issue by asingingbird** [alessandromaggio/pythonping#55]
Deos pythonping support python2 ? If not, why can I install it ?
I'm not sure it's a bug or pythonping is not compatible with python2.

I install pythonping with command `pip install pythonping`, when trying to import it, I got this error:
```
% sudo python
Password:

WARNING: Python 2.7 is not recommended.
This version is included in macOS for compatibility with legacy software.
Future versions of macOS will not include Python 2.7.
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Jun  5 2020, 22:59:21)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythonping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asingingbird/Library/Python/2.7/lib/python/site-packages/pythonping/__init__.py", line 2, in <module>
    from . import network, executor, payload_provider
  File "/Users/asingingbird/Library/Python/2.7/lib/python/site-packages/pythonping/executor.py", line 201
    print(value, file=self.output)
                     ^
SyntaxError: invalid syntax
```

**Comment by malbers15** [comment]
Hi @asingingbird 

The error is due to the print syntax difference from python2 to python3.  We also took the decision to not support python2 as it was officially deprecated as of January 1st, 2020:
https://www.python.org/doc/sunset-python-2/

https://github.com/alessandromaggio/pythonping/issues/50
https://github.com/alessandromaggio/pythonping/pull/52#issuecomment-679468589

**Comment by asingingbird** [comment]
Thanks @malbers15 
Stubborn Apple still using Python2 as default though, do you think it is necessary to mention this in the document? Or adding a description like "Requires: Python >=3.6" at PyPI.

**Comment by malbers15** [comment]
@asingingbird I don't think so because the phasing out of python2 has been in progress for years now with a targeted end date.  Even your terminal warns against it and gives a good explanation:
```
% sudo python
Password:

WARNING: Python 2.7 is not recommended.
This version is included in macOS for compatibility with legacy software.
Future versions of macOS will not include Python 2.7.
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Jun  5 2020, 22:59:21)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

I would just use the `python3` option from the terminal, which is what Linux users do too (until the phase out of python2 is phased out of old legacy software support completely).  And if you install a python 3 line on Windows and add it to the path, you will be able to type `python` at the command line and get your python 3 install.

**Comment by asingingbird** [comment]
@malbers15 
Fair point, time for everyone to forget Python2 ever existed, it's the best for both library developers and users.
BTW, I set default Python to Python3 from within terminal using [pyenv](https://github.com/pyenv/pyenv) on my Mac.

**Comment by malbers15** [comment]
@asingingbird changing the environment variable sounds like a great work around
