### ISSUE TITLE
TTL

### ISSUE THREAD

**Issue by konserw** [alessandromaggio/pythonping#61]
Hi!
Could you please add TTL value to ResponseList ? 
Background:
I'm using TTL to check if ping target is windows or linux machine (usually <64 for linux and > 64 for windows)
Now I'm using subprocess + regex and I would like to switch over to pythonping instead ;)

Cheers!

**Comment by alessandromaggio** [comment]
Hi!

How would you implement such a thing? Each response may have a different TTL indeed, so what would it be the TTL for a group of responses (aka ResponseList)?

It is dangerous to assume the TTL will be constant between responses from the same host because it does not depend exclusively on device settings, but also on network conditions which may vary over time and are unpredictable.

**Comment by BlankHat1610** [comment]
Hi!
I know it's dangerous, but it's necessary to add it in the response list, because even today losts of program still need it for there purpose.

**Comment by alessandromaggio** [comment]
We cannot implement a feature that is unstable by design in our stable version. If you really need to guess the OS, you can do that by fetching the first Response from ResponseList, but ResponseList has no TTL because it is a property of the response by its own nature.

We may consider adding an average TTL on ResponseList, but that would be a different request - feel free to create a PR for that.
