### ISSUE TITLE
ping to a server's specific port (e. g. 142.251.33.110:7777)

### ISSUE THREAD

**Issue by Zenahr** [alessandromaggio/pythonping#73]
I'm writing a matchmaking server for game developers at the moment. To make sure the serverlist is not filled with dead servers I thought I could ping the client computers using pythonping. With the current implementation however the list would be incorrect since it would require users to completely turn off their computers.

The game servers are run by my clients (players) and the game servers' ports would be `7777` or `7778`.
Now, in the event of a user's PC crashing my matchmaking server would not receive a request to remove the client server from the list. For that case I'd need to check the IP-address + Port to ensure the server is dead.

**Describe the solution you'd like**
An additional, optional parameter named `port` on the `ping()` method allowing us to ping servers not just via the ip-address alone but also the port.

My knowledge on IPs and ports is limited so perhaps it's technically not even possible to check if a specific port is a live.

**Comment by alessandromaggio** [comment]
Hello, thanks for asking. Unlike what you may see in gaming context, at a network level pings are ICMP messages that are encapsulated directly into IP packets. Ports are a concept used in TCP and UDP, which ICMP does not use. It may be possible to "ping" a server over TCP, because it is possible to trigger a connection and if the server is listening it will reply. However, this is simply not possible with UDP because a message sent does not necessarily require a reply back, so you have no way to know if the server is listening.

Having that said, the best solution for you to "ping" a port (provided the server is listening using TCP), is to check if a *telnet* connection opens on that port - and there are plenty of libraries for that. At the moment this feature would be outside of the core package of pythonping.

I hope I have been of help!
